# python3 PolicySimulation.py VI/policy_values/VIp_3_3.pkl
# python3 PolicySimulation.py 'Convex Policy e_version/policy/C_Agent_Policy_ni_3_3_3.pkl'
# python3 PolicySimulation.py 'Convex Policy e_version/policy/C_Agent_Policy_ni_1_3_3.pkl'
# python3 PolicySimulation.py 'Non-Convex Policy e_version/policy/NC_Agent_Policy_ni_1_3_3.pkl'
# python3 PolicySimulation.py 'Non-Convex Policy e_version/policy/NC_Agent_Policy_ni_3_3_3.pkl'
python3 PolicySimulation.py 'Non-Convex Policy e_version/policy/NC_Agent_Policy_fc_3_3_3.pkl'
# python3 PolicySimulation.py 'Non-Convex Policy/policy/NC_Agent_Policy_nor_1_3_3.pkl'
# python3 PolicySimulation.py 'Non-Convex Policy/policy/NC_Agent_Policy_nor_3_3_3.pkl'
# python3 PolicySimulation.py 'Non-Convex Policy/policy/NC_Agent_Policy_nor_ni_1_3_3.pkl'
# python3 PolicySimulation.py 'Non-Convex Policy/policy/NC_Agent_Policy_nor_ni_3_3_3.pkl'
# python3 PolicySimulation.py 'Dual LP - Gekko/policy/NC_Agent_Policy_no_upper_3_31.pkl'
# python3 PolicySimulation.py 'Dual LP - Gekko/policy/NC_Agent_Policy_no_upper_3_32.pkl'
# python3 PolicySimulation.py 'Dual LP - Gekko/policy/NC_Agent_Policy_no_upper_3_33.pkl'